### ISSUE TITLE
Vergleich von Ticketsystemen

### ISSUE THREAD

**Issue by marcelthole** [lngn-agile-meetup/lngn-agile-meetup.github.io#1]
Es wäre ein Talk wünschenswert, welcher verschiedene Ticketsysteme vergleicht.

- Jira (https://de.atlassian.com/software/jira)
- phabricator (https://www.phacility.com/) Demo: https://phabricator.wikimedia.org/
- Gitlab (https://about.gitlab.com/)
- OpenProject (https://www.openproject.org/de/)
- Redmine (https://www.redmine.org/)
- Trac (https://trac.edgewall.org/)

**Comment by woldinius** [comment]
JIRA, Gitlab, OpenProject, Redmine -> Done.

**Comment by woldinius** [comment]
Done in 2018
